# Generated by Django 5.2.5 on 2025-08-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("gender", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name_plural": "employees",
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="FactoryUnit",
            fields=[
                ("unit_id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "factory units",
                "db_table": "factory_unit",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=55)),
                ("packaging_units", models.CharField(max_length=10)),
                ("number_of_units_per_pack", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "products",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("status_name", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name_plural": "statuses",
                "db_table": "status",
            },
        ),
        migrations.CreateModel(
            name="BleachingProcess",
            fields=[
                (
                    "idbleaching_process",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("shift", models.CharField(max_length=9)),
                ("comments", models.CharField(max_length=255)),
                ("number_of_cakes_to_rebleached", models.IntegerField()),
                ("number_of_rebleach_added", models.IntegerField()),
                (
                    "production_chemist_employee",
                    models.ForeignKey(
                        db_column="production_chemist_employee_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bleaching_processes_as_chemist",
                        to="populator.employees",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "bleaching processes",
                "db_table": "bleaching_process",
            },
        ),
        migrations.AddField(
            model_name="employees",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="unit_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="populator.factoryunit",
            ),
        ),
        migrations.CreateModel(
            name="KierProcessors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.ForeignKey(
                        db_column="batch_number",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="populator.bleachingprocess",
                        to_field="batch_number",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="populator.employees",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "kier processors",
                "db_table": "kier_processors",
                "unique_together": {("batch_number", "employee")},
            },
        ),
        migrations.AddField(
            model_name="bleachingprocess",
            name="processors",
            field=models.ManyToManyField(
                related_name="bleaching_processes_as_processor",
                through="populator.KierProcessors",
                to="populator.employees",
            ),
        ),
        migrations.CreateModel(
            name="Productions",
            fields=[
                ("production_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("batch_number", models.CharField(max_length=10)),
                ("shift", models.CharField(default="NA", max_length=15)),
                ("production_line", models.CharField(max_length=1)),
                ("quantity_produced", models.IntegerField()),
                ("packaging_supervisor", models.CharField(max_length=45)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "supervisor_employee",
                    models.ForeignKey(
                        db_column="supervisor_employee_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="populator.employees",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="populator.products",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "productions",
                "db_table": "productions",
            },
        ),
        migrations.AddField(
            model_name="employees",
            name="status",
            field=models.ForeignKey(
                db_column="status_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="populator.status",
            ),
        ),
        migrations.CreateModel(
            name="TransferItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_transferred", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="populator.products",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transfer items",
                "db_table": "transfer_items",
            },
        ),
        migrations.CreateModel(
            name="Transfers",
            fields=[
                ("transfer_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("transfer_time", models.TimeField()),
                ("production_line", models.CharField(max_length=1)),
                ("notes", models.CharField(blank=True, max_length=750, null=True)),
                (
                    "products",
                    models.ManyToManyField(
                        through="populator.TransferItems", to="populator.products"
                    ),
                ),
                (
                    "supervisor_employee",
                    models.ForeignKey(
                        db_column="supervisor_employee_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="populator.employees",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transfers",
                "db_table": "transfers",
            },
        ),
        migrations.AddField(
            model_name="transferitems",
            name="transfer",
            field=models.ForeignKey(
                db_column="transfer_id",
                on_delete=django.db.models.deletion.RESTRICT,
                to="populator.transfers",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transferitems",
            unique_together={("transfer", "product")},
        ),
    ]
